### Create new barber
POST http://localhost:8080/barber/create
Content-Type: application/json

{
  "phone": "barberPhoneNew",
  "email": "barberEmailNew",
  "barberStatus": "WORK"
}

### Change barber status via id and status
PUT http://localhost:8080/barber/change?status=work&id=2
Content-Type: application/x-www-form-urlencoded